version: '3.2'

services:
  server:
    build: ./
    depends_on:
      - db
    volumes:
      - ./:/usr/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules/
    ports:
      - "${CLIENT_PORT}:3000"
    command: npm start
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
